### PR TITLE
Mqtt library update, mqtt logging and build flags

### PR DESCRIPTION
**Pull request by forsberg**
* Had trouble building a binary that would work in the docker flag. Added static flags. Might have been a go-version-related thing, it now works with my go 1.12.10.
* Added some logging calls for the mqtt library to aid in debugging problems.
* Updated mqtt libraries to latest version, as I had problems with the exporter just stopping when talking to a recent version of mosquitto.

### CODE REVIEW

**Comment by Legion2** [comment]
I created #27 where I updated to go 1.14 and use the new go module system

**Comment by forsberg** [comment]
@Legion2 - noticed that now. That is of course the better option, but my go skills were not good enough to make this happen :-)

I'll close this PR, and make a new one based on your PR, adding the logging and updating MQTT library.

**Comment by forsberg** [comment]
See #29.

**Comment by Legion2** [comment]
@forsberg this is my first time doing something with go and I had to figure out that there is no official package system until 1.14.

**Pull request closed without merging**
